[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
cli.workspace = true

clap.workspace = true
thiserror.workspace = true
futures.workspace = true
ratatui.workspace = true
tokio.workspace = true
crossterm.workspace = true
